require File.dirname(__FILE__) + "/../../spec_helper"

module CacheModel
  describe KeywordUppercaser do
    before :each do
      @upper_caser = KeywordUppercaser
      @keywords = @upper_caser.keywords
    end
    
    keywords = [
      "ADD",
      "ALL",
      "ALTER",
      "ANALYZE",
      "AND",
      "AS",
      "ASC",
      "ASENSITIVE",
      "BEFORE",
      "BETWEEN",
      "BIGINT",
      "BINARY",
      "BLOB",
      "BOTH",
      "BY",
      "CALL",
      "CASCADE",
      "CASE",
      "CHANGE",
      "CHAR",
      "CHARACTER",
      "CHECK",
      "COLLATE",
      "COLUMN",
      "CONDITION",
      "CONSTRAINT",
      "CONTINUE",
      "CONVERT",
      "CREATE",
      "CROSS",
      "CURRENT_DATE",
      "CURRENT_TIME",
      "CURRENT_TIMESTAMP",
      "CURRENT_USER",
      "CURSOR",
      "DATABASE",
      "DATABASES",
      "DAY_HOUR",
      "DAY_MICROSECOND",
      "DAY_MINUTE",
      "DAY_SECOND",
      "DEC",
      "DECIMAL",
      "DECLARE",
      "DEFAULT",
      "DELAYED",
      "DELETE",
      "DESC",
      "DESCRIBE",
      "DETERMINISTIC",
      "DISTINCT",
      "DISTINCTROW",
      "DIV",
      "DOUBLE",
      "DROP",
      "DUAL",
      "EACH",
      "ELSE",
      "ELSEIF",
      "ENCLOSED",
      "ESCAPED",
      "EXISTS",
      "EXIT",
      "EXPLAIN",
      "FALSE",
      "FETCH",
      "FLOAT",
      "FLOAT4",
      "FLOAT8",
      "FOR",
      "FORCE",
      "FOREIGN",
      "FROM",
      "FULLTEXT",
      "GRANT",
      "GROUP",
      "HAVING",
      "HIGH_PRIORITY",
      "HOUR_MICROSECOND",
      "HOUR_MINUTE",
      "HOUR_SECOND",
      "IF",
      "IGNORE",
      "IN",
      "INDEX",
      "INFILE",
      "INNER",
      "INOUT",
      "INSENSITIVE",
      "INSERT",
      "INT",
      "INT1",
      "INT2",
      "INT3",
      "INT4",
      "INT8",
      "INTEGER",
      "INTERVAL",
      "INTO",
      "IS",
      "ITERATE",
      "JOIN",
      "KEY",
      "KEYS",
      "KILL",
      "LEADING",
      "LEAVE",
      "LEFT",
      "LIKE",
      "LIMIT",
      "LINES",
      "LOAD",
      "LOCALTIME",
      "LOCALTIMESTAMP",
      "LOCK",
      "LONG",
      "LONGBLOB",
      "LONGTEXT",
      "LOOP",
      "LOW_PRIORITY",
      "MATCH",
      "MEDIUMBLOB",
      "MEDIUMINT",
      "MEDIUMTEXT",
      "MIDDLEINT",
      "MINUTE_MICROSECOND",
      "MINUTE_SECOND",
      "MOD",
      "MODIFIES",
      "NATURAL",
      "NOT",
      "NO_WRITE_TO_BINLOG",
      "NULL",
      "NUMERIC",
      "ON",
      "OPTIMIZE",
      "OPTION",
      "OPTIONALLY",
      "OR",
      "ORDER",
      "OUT",
      "OUTER",
      "OUTFILE",
      "PRECISION",
      "PRIMARY",
      "PROCEDURE",
      "PURGE",
      "READ",
      "READS",
      "REAL",
      "REFERENCES",
      "REGEXP",
      "RELEASE",
      "RENAME",
      "REPEAT",
      "REPLACE",
      "REQUIRE",
      "RESTRICT",
      "RETURN",
      "REVOKE",
      "RIGHT",
      "RLIKE",
      "SCHEMA",
      "SCHEMAS",
      "SECOND_MICROSECOND",
      "SELECT",
      "SENSITIVE",
      "SEPARATOR",
      "SET",
      "SHOW",
      "SMALLINT",
      "SONAME",
      "SPATIAL",
      "SPECIFIC",
      "SQL",
      "SQLEXCEPTION",
      "SQLSTATE",
      "SQLWARNING",
      "SQL_BIG_RESULT",
      "SQL_CALC_FOUND_ROWS",
      "SQL_SMALL_RESULT",
      "SSL",
      "STARTING",
      "STRAIGHT_JOIN",
      "TABLE",
      "TERMINATED",
      "THEN",
      "TINYBLOB",
      "TINYINT",
      "TINYTEXT",
      "TO",
      "TRAILING",
      "TRIGGER",
      "TRUE",
      "UNDO",
      "UNION",
      "UNIQUE",
      "UNLOCK",
      "UNSIGNED",
      "UPDATE",
      "USAGE",
      "USE",
      "USING",
      "UTC_DATE",
      "UTC_TIME",
      "UTC_TIMESTAMP",
      "VALUES",
      "VARBINARY",
      "VARCHAR",
      "VARCHARACTER",
      "VARYING",
      "WHEN",
      "WHERE",
      "WHILE",
      "WITH",
      "WRITE",
      "XOR",
      "YEAR_MONTH",
      "ZEROFILL",
      "ASENSITIVE",
      "CALL",
      "CONDITION",
      "CONNECTION",
      "CONTINUE",
      "CURSOR",
      "DECLARE",
      "DETERMINISTIC",
      "EACH",
      "ELSEIF",
      "EXIT",
      "FETCH",
      "GOTO",
      "INOUT",
      "INSENSITIVE",
      "ITERATE",
      "LABEL",
      "LEAVE",
      "LOOP",
      "MODIFIES",
      "OUT",
      "READS",
      "RELEASE",
      "REPEAT",
      "RETURN",
      "SCHEMA",
      "SCHEMAS",
      "SENSITIVE",
      "SPECIFIC",
      "SQL",
      "SQLEXCEPTION",
      "SQLSTATE",
      "SQLWARNING",
      "TRIGGER",
      "UNDO",
      "UPGRADE",
      "WHILE"
    ]
    
    keywords.each do |keyword|
      it "should have the keyword '#{keyword}'" do
        @keywords.should include(keyword.to_sym)
      end
    end

    def upcase(string)
      @upper_caser.new(string).upcase
    end
    
    it "should upcase the word 'select'" do
      upcase("select").should == "SELECT"
    end
    
    it "should not upcase a word which is not a keyword" do
      upcase("foobar").should == "foobar"
    end
    
    it "should only upcase the keyword in a string" do
      upcase("select foobar").should == "SELECT foobar"
    end

    it "should not upcase a word inside single quotes" do
      upcase("select * from 'sql'").should == "SELECT * FROM 'sql'"
    end

    it "should not upcase a word inside double (backslash) quotes" do
      upcase("select * from \"sql\"").should == "SELECT * FROM \"sql\""
    end

    it "should upcase the word SQL" do
      upcase("sql").should == "SQL"
    end

    it "should not upcase a word inside double quotes" do 
      upcase('select * from "sql"').should == "SELECT * FROM \"sql\""
    end

    it "should not upcase any of the words inside a set of two word double quotes" do
      upcase('select * from "my sql"').should == 'SELECT * FROM "my sql"'
    end

    it "should not upcase any of the words inside a set of three word double quotes" do
      upcase('select * from "my sql foo"').should == 'SELECT * FROM "my sql foo"'
    end
    
  end
end 
